// src/components/curriculum/lehrplanData.js

// Lehrplan für Deutsch (extrahiert aus TopicsView)
export const getLehrplanDeutsch = () => {
  return [
    { kompetenz_id: "D.1.A.1a", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Laute, Silben, Stimmen wahrnehmen", beschreibung: "können die Aufmerksamkeit auf die sprechende Person und deren Beitrag richten.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Hören", "Aufmerksamkeit", "Grundfertigkeiten"] },
    { kompetenz_id: "D.1.A.1b", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Laute, Silben, Stimmen wahrnehmen", beschreibung: "können Klänge, Geräusche sowie Reime, Silben und einzelne Laute (z.B. Anlaute) heraushören (phonologische Bewusstheit).", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Hören", "Phonologische Bewusstheit"] },
    { kompetenz_id: "D.1.A.1c", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Laute, Silben, Stimmen wahrnehmen", beschreibung: "können den Tonfall einer Stimme in der entsprechenden Situation deuten (z.B. Lautstärke, Geschwindigkeit, Stimmlage).", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Hören", "Tonfall", "Interpretation"] },
    { kompetenz_id: "D.1.A.1e", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Laute, Silben, Stimmen wahrnehmen", beschreibung: "können nonverbale Mittel (z.B. Gestik, Mimik, Körperhaltung) und paraverbale Mittel (z.B. Intonation, Sprechfluss) in der Hörsituation deuten.", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Hören", "Nonverbale Kommunikation"] },
    { kompetenz_id: "D.1.A.2f", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Laute, Silben, Stimmen wahrnehmen", beschreibung: "können in anforderungsreichen Situationen (z.B. Zeitdruck, Nebengeräusche) Emotionen der sprechenden Person einschätzen.", zyklus: "2", reihenfolge_index: "f", schluesselwoerter: ["Hören", "Emotionen", "Situationen"] },
    { kompetenz_id: "D.1.B.1a", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "B Verstehen in monologischen Hörsituationen", kompetenz_titel: "Wichtige Informationen aus Hörtexten entnehmen", beschreibung: "können einfache Aufträge und Erklärungen zu bekannten Sachthemen und Alltagssituationen verstehen und ausführen (z.B. alltägliche Abläufe).", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Hören", "Verstehen", "Aufträge"] },
    { kompetenz_id: "D.1.B.1c", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "B Verstehen in monologischen Hörsituationen", kompetenz_titel: "Wichtige Informationen aus Hörtexten entnehmen", beschreibung: "können Mitteilungen und Erklärungen verstehen und Aufträge ausführen.", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Hören", "Mitteilungen", "Aufträge"] },
    { kompetenz_id: "D.1.B.2e", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "B Verstehen in monologischen Hörsituationen", kompetenz_titel: "Wichtige Informationen aus Hörtexten entnehmen", beschreibung: "können mit Unterstützung eine Hörerwartung aufbauen (z.B. Vorwissen aktivieren, durch vorheriges Lesen der Hörverständnis-Fragen).", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Hören", "Hörerwartung", "Strategien"] },
    { kompetenz_id: "D.1.B.2f", fach_name: "Deutsch", hauptbereich: "D.1 Hören", unterbereich: "B Verstehen in monologischen Hörsituationen", kompetenz_titel: "Wichtige Informationen aus Hörtexten entnehmen", beschreibung: "können unter Anleitung wichtige, auch implizite Informationen eines Hörtextes verstehen und wiedergeben (z.B. Bericht, Vortrag, Hörspiel).", zyklus: "2", reihenfolge_index: "f", schluesselwoerter: ["Hören", "Implizite Informationen"] },
    { kompetenz_id: "D.2.A.1a", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Grundfertigkeiten des Lesens", beschreibung: "können Piktogramme und einfache Wortbilder aus ihrem Alltagsleben wieder erkennen (z.B. Migros, Coop, Volg, Coca Cola).", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Lesen", "Piktogramme", "Wortbilder"] },
    { kompetenz_id: "D.2.A.1b", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Grundfertigkeiten des Lesens", beschreibung: "können die passende Beziehung zwischen Buchstaben und Lauten herstellen sowie Buchstaben zu Silben und kurzen Wörtern aus dem schulnahen Wortschatz verbinden.", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Lesen", "Buchstaben", "Laute"] },
    { kompetenz_id: "D.2.A.1c", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Grundfertigkeiten des Lesens", beschreibung: "erkennen vertraute Wörter auf einen Blick (Sichtwortschatz).", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Lesen", "Sichtwortschatz"] },
    { kompetenz_id: "D.2.A.2f", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Grundfertigkeiten des Lesens", beschreibung: "können einen längeren geübten Text flüssig vorlesen.", zyklus: "2", reihenfolge_index: "f", schluesselwoerter: ["Lesen", "Vorlesen", "Flüssigkeit"] },
    { kompetenz_id: "D.2.B.1a", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "B Verstehen von Sachtexten", kompetenz_titel: "Wichtige Informationen aus Sachtexten entnehmen", beschreibung: "können einfache Sachverhalte in Bildern und Aufträge in Bildform verstehen.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Lesen", "Sachtexte", "Bilder"] },
    { kompetenz_id: "D.2.B.1c", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "B Verstehen von Sachtexten", kompetenz_titel: "Wichtige Informationen aus Sachtexten entnehmen", beschreibung: "können Abbildungen und Text bei bebilderten Sachtexten zueinander in Beziehung setzen.", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Lesen", "Sachtexte", "Abbildungen"] },
    { kompetenz_id: "D.2.B.2e", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "B Verstehen von Sachtexten", kompetenz_titel: "Wichtige Informationen aus Sachtexten entnehmen", beschreibung: "können übersichtliche Sachtexte mit Fotos und Abbildungen überblicken.", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Lesen", "Sachtexte", "Überblick"] },
    { kompetenz_id: "D.2.B.2f", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "B Verstehen von Sachtexten", kompetenz_titel: "Wichtige Informationen aus Sachtexten entnehmen", beschreibung: "können die Struktur eines Textes erkennen und explizite Informationen entnehmen.", zyklus: "2", reihenfolge_index: "f", schluesselwoerter: ["Lesen", "Textstruktur", "Informationen"] },
    { kompetenz_id: "D.2.C.1a", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "C Verstehen literarischer Texte", kompetenz_titel: "Literarische Texte lesen und verstehen", beschreibung: "können in einem Bild eine Situation erkennen (z.B. Figur, Handlung, mögliche Geschichte).", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Lesen", "Literatur", "Bilder"] },
    { kompetenz_id: "D.2.C.1b", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "C Verstehen literarischer Texte", kompetenz_titel: "Literarische Texte lesen und verstehen", beschreibung: "können erzählte und vorgelesene Texte verstehen und darin den Handlungsstrang erkennen (z.B. kleine Geschichte, Bilderbuch, Vers, Abzählreim).", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Lesen", "Literatur", "Handlung"] },
    { kompetenz_id: "D.2.C.2e", fach_name: "Deutsch", hauptbereich: "D.2 Lesen", unterbereich: "C Verstehen literarischer Texte", kompetenz_titel: "Literarische Texte lesen und verstehen", beschreibung: "können mit Unterstützung aufgrund von Cover, Klappentext, Illustrationen und Textausschnitten, (Hör-)Bücher und andere Medien auswählen.", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Lesen", "Literatur", "Medienauswahl"] },
    { kompetenz_id: "D.3.A.1a", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Sprechmotorik, Artikulation nutzen", beschreibung: "können die meisten Laute des Deutschen sprechmotorisch isoliert und im Wort bilden.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Sprechen", "Artikulation", "Laute"] },
    { kompetenz_id: "D.3.A.1b", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Sprechmotorik, Artikulation nutzen", beschreibung: "können mit verständlicher Aussprache und angemessener Lautstärke in Standardsprache (nach-)sprechen, wobei die Sprechweise auch mundartlich und erstsprachlich gefärbt sein kann.", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Sprechen", "Standardsprache", "Aussprache"] },
    { kompetenz_id: "D.3.A.2d", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "Sprechmotorik, Artikulation nutzen", beschreibung: "können das Zusammenspiel von Verbalem, Paraverbalem und Nonverbalem gestalten.", zyklus: "2", reihenfolge_index: "d", schluesselwoerter: ["Sprechen", "Kommunikation", "Nonverbal"] },
    { kompetenz_id: "D.3.B.1a", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "B Monologisches Sprechen", kompetenz_titel: "In monologischen Situationen verständlich ausdrücken", beschreibung: "können ihre Gefühle und Gedanken sowie Erlebnisse und Erfahrungen verbal oder nonverbal mit Unterstützung zum Ausdruck bringen.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Sprechen", "Gefühle", "Erlebnisse"] },
    { kompetenz_id: "D.3.B.1c", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "B Monologisches Sprechen", kompetenz_titel: "In monologischen Situationen verständlich ausdrücken", beschreibung: "können sich in Mundart und Standardsprache ausdrücken, wobei erstsprachliche und mundartliche Elemente selbstverständlich sind.", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Sprechen", "Mundart", "Standardsprache"] },
    { kompetenz_id: "D.3.B.2e", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "B Monologisches Sprechen", kompetenz_titel: "In monologischen Situationen verständlich ausdrücken", beschreibung: "können Strukturierungshilfen für eine Kurzpräsentation nutzen (z.B. Mindmap, Gliederung, Stichworte).", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Sprechen", "Präsentation", "Strukturierung"] },
    { kompetenz_id: "D.3.B.3h", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "B Monologisches Sprechen", kompetenz_titel: "In monologischen Situationen verständlich ausdrücken", beschreibung: "können sich in der Standardsprache weitgehend sicher ausdrücken, wobei einzelne erstsprachliche und mundartliche Elemente vorkommen können.", zyklus: "3", reihenfolge_index: "h", schluesselwoerter: ["Sprechen", "Standardsprache", "Präsentation"] },
    { kompetenz_id: "D.3.C.1a", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "C Dialogisches Sprechen", kompetenz_titel: "Sich aktiv an einem Dialog beteiligen", beschreibung: "können die/den Gesprächspartner/in als Gegenüber wahrnehmen und mit ihr/ihm in Kontakt treten.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Sprechen", "Dialog", "Kontakt"] },
    { kompetenz_id: "D.3.C.1b", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "C Dialogisches Sprechen", kompetenz_titel: "Sich aktiv an einem Dialog beteiligen", beschreibung: "können auf direkt an sie gerichtete Fragen antworten.", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Sprechen", "Fragen", "Antworten"] },
    { kompetenz_id: "D.3.C.2d", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "C Dialogisches Sprechen", kompetenz_titel: "Sich aktiv an einem Dialog beteiligen", beschreibung: "können sich in längeren Gesprächen angemessen einbringen und thematisch passende Beiträge beisteuern.", zyklus: "2", reihenfolge_index: "d", schluesselwoerter: ["Sprechen", "Gespräche", "Beiträge"] },
    { kompetenz_id: "D.3.C.3g", fach_name: "Deutsch", hauptbereich: "D.3 Sprechen", unterbereich: "C Dialogisches Sprechen", kompetenz_titel: "Sich aktiv an einem Dialog beteiligen", beschreibung: "können im Gespräch auf vorhergehende Aussagen Bezug nehmen.", zyklus: "3", reihenfolge_index: "g", schluesselwoerter: ["Sprechen", "Bezug nehmen", "Dialog"] },
    { kompetenz_id: "D.4.A.1c", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "In persönlicher Handschrift leserlich schreiben", beschreibung: "können die Grundbewegungen der Schrift nach allen Richtungen (z.B. Buchstabenformen und -folgen) ausführen.", zyklus: "1", reihenfolge_index: "c", schluesselwoerter: ["Schreiben", "Handschrift", "Grundbewegungen"] },
    { kompetenz_id: "D.4.A.1d", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "In persönlicher Handschrift leserlich schreiben", beschreibung: "können das ganze Alphabet einer unverbundenen Schrift sowie die Ziffern mit optimalen Abläufen geläufig schreiben.", zyklus: "1", reihenfolge_index: "d", schluesselwoerter: ["Schreiben", "Alphabet", "Handschrift"] },
    { kompetenz_id: "D.4.A.2g", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "A Grundfertigkeiten", kompetenz_titel: "In persönlicher Handschrift leserlich schreiben", beschreibung: "können in einer leserlichen, geläufigen und persönlichen Handschrift schreiben.", zyklus: "2", reihenfolge_index: "g", schluesselwoerter: ["Schreiben", "Handschrift", "Geläufigkeit"] },
    { kompetenz_id: "D.4.E.1a", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "E Schreibprozess: inhaltlich überarbeiten", kompetenz_titel: "Text inhaltlich überarbeiten", beschreibung: "können inhaltliche Unklarheiten besprechen, wenn die Lehrperson auf die entsprechenden Textstellen hinweist.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Schreiben", "Überarbeiten", "Unklarheiten"] },
    { kompetenz_id: "D.4.E.2b", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "E Schreibprozess: inhaltlich überarbeiten", kompetenz_titel: "Text inhaltlich überarbeiten", beschreibung: "können im Austausch mit anderen (z.B. Schreibkonferenz, Feedback) einzelne positive Aspekte und Unstimmigkeiten im eigenen Text erkennen.", zyklus: "2", reihenfolge_index: "b", schluesselwoerter: ["Schreiben", "Feedback", "Schreibkonferenz"] },
    { kompetenz_id: "D.4.E.2d", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "E Schreibprozess: inhaltlich überarbeiten", kompetenz_titel: "Text inhaltlich überarbeiten", beschreibung: "können einzelne vorher besprochene Punkte in ihren Texten mithilfe von Kriterien am Computer oder auf Papier überarbeiten.", zyklus: "2", reihenfolge_index: "d", schluesselwoerter: ["Schreiben", "Überarbeiten", "Kriterien"] },
    { kompetenz_id: "D.4.E.3f", fach_name: "Deutsch", hauptbereich: "D.4 Schreiben", unterbereich: "E Schreibprozess: inhaltlich überarbeiten", kompetenz_titel: "Text inhaltlich überarbeiten", beschreibung: "können im Austausch mit anderen am Computer oder auf Papier positive Aspekte erkennen sowie Unstimmigkeiten in Bezug auf ihr Schreibziel und Textsortenvorgaben feststellen und mit Hilfsmitteln Alternativen finden (z.B. Wörterbuch, Internet).", zyklus: "3", reihenfolge_index: "f", schluesselwoerter: ["Schreiben", "Überarbeiten", "Textsorten"] },
    { kompetenz_id: "D.5.A.1a", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "A Verfahren und Proben", kompetenz_titel: "Sprache erforschen und vergleichen", beschreibung: "können sprachliches Material nach vorgegebenen Kriterien auswählen und ordnen (z.B. Wörter nach Anlaut sortieren, Reime ordnen, Wörter zu Begriffsfeld sammeln, Grussformen sammeln).", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Sprache", "Erforschen", "Ordnen"] },
    { kompetenz_id: "D.5.A.2b", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "A Verfahren und Proben", kompetenz_titel: "Sprache erforschen und vergleichen", beschreibung: "können sprachliches Material aus einer vorgegebenen Sammlung auswählen oder dieses aus einer oder mehreren Sprachen selber erstellen.", zyklus: "2", reihenfolge_index: "b", schluesselwoerter: ["Sprache", "Sammeln", "Vergleichen"] },
    { kompetenz_id: "D.5.A.3c", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "A Verfahren und Proben", kompetenz_titel: "Sprache erforschen und vergleichen", beschreibung: "können selbstständig Ersatz-, Verschiebe-, Erweiterungs- und Weglassprobe anwenden, um Sprachstrukturen (nach formalen Kriterien) zu untersuchen.", zyklus: "3", reihenfolge_index: "c", schluesselwoerter: ["Sprache", "Proben", "Sprachstrukturen"] },
    { kompetenz_id: "D.5.D.1a", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "D Grammatikbegriffe", kompetenz_titel: "Grammatikbegriffe für Analyse anwenden", beschreibung: "können erste Erfahrungen mit den drei Hauptwortarten Nomen, Verb und Adjektiv sammeln.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Grammatik", "Wortarten", "Nomen", "Verb", "Adjektiv"] },
    { kompetenz_id: "D.5.D.2b", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "D Grammatikbegriffe", kompetenz_titel: "Grammatikbegriffe für Analyse anwenden", beschreibung: "können typische Nomen, Verben und Adjektive mithilfe inhaltlicher Proben bestimmen.", zyklus: "2", reihenfolge_index: "b", schluesselwoerter: ["Grammatik", "Wortarten", "Proben"] },
    { kompetenz_id: "D.5.D.3e", fach_name: "Deutsch", hauptbereich: "D.5 Sprache(n) im Fokus", unterbereich: "D Grammatikbegriffe", kompetenz_titel: "Grammatikbegriffe für Analyse anwenden", beschreibung: "können Präpositionen mithilfe einer reduzierten Liste benennen.", zyklus: "3", reihenfolge_index: "e", schluesselwoerter: ["Grammatik", "Präpositionen"] },
    { kompetenz_id: "D.6.A.1a", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "A Auseinandersetzung mit literarischen Texten", kompetenz_titel: "Spielerisch und kreativ mit literarischen Texten umgehen", beschreibung: "können in vorgelesene und erzählte Geschichten mit Unterstützung von Bilderbüchern eintauchen.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Literatur", "Geschichten", "Bilderbücher"] },
    { kompetenz_id: "D.6.A.1b", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "A Auseinandersetzung mit literarischen Texten", kompetenz_titel: "Spielerisch und kreativ mit literarischen Texten umgehen", beschreibung: "können zu Geschichten zeichnen und spielen. Sie können die entstandenen Zeichnungen und Handlungen in Bezug zur Geschichte setzen und einzelne Episoden daraus erzählen.", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Literatur", "Zeichnen", "Spielen"] },
    { kompetenz_id: "D.6.A.2d", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "A Auseinandersetzung mit literarischen Texten", kompetenz_titel: "Spielerisch und kreativ mit literarischen Texten umgehen", beschreibung: "können die Sichtweise einzelner Figuren erkennen und sich in sie hineinversetzen (z.B. indem sie die Figuren darstellend spielen).", zyklus: "2", reihenfolge_index: "d", schluesselwoerter: ["Literatur", "Perspektive", "Figuren"] },
    { kompetenz_id: "D.6.A.3g", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "A Auseinandersetzung mit literarischen Texten", kompetenz_titel: "Spielerisch und kreativ mit literarischen Texten umgehen", beschreibung: "können die Innensicht und Gedanken von Figuren in eindeutigen Situationen erkennen und imaginieren (z.B. szenische Darstellung, innerer Monolog).", zyklus: "3", reihenfolge_index: "g", schluesselwoerter: ["Literatur", "Innensicht", "Figuren"] },
    { kompetenz_id: "D.6.B.1a", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "B Auseinandersetzung mit verschiedenen Autor/innen", kompetenz_titel: "Autor/innen und Texte aus verschiedenen Kulturen kennen", beschreibung: "können Erfahrungen sammeln mit literarischen Texten (z.B. Lied, Vers, Bilderbuch, Märchen, Audiotext, Film) aus der eigenen Kultur und aus anderen Kulturen und unter Anleitung darüber sprechen.", zyklus: "1", reihenfolge_index: "a", schluesselwoerter: ["Literatur", "Kulturen", "Vielfalt"] },
    { kompetenz_id: "D.6.B.2b", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "B Auseinandersetzung mit verschiedenen Autor/innen", kompetenz_titel: "Autor/innen und Texte aus verschiedenen Kulturen kennen", beschreibung: "kennen einzelne Autor/innen der Kinderliteratur und einzelne Aspekte aus deren Leben.", zyklus: "2", reihenfolge_index: "b", schluesselwoerter: ["Literatur", "Autor/innen", "Kinderliteratur"] },
    { kompetenz_id: "D.6.B.3e", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "B Auseinandersetzung mit verschiedenen Autor/innen", kompetenz_titel: "Autor/innen und Texte aus verschiedenen Kulturen kennen", beschreibung: "können über einzelne bedeutende Autor/innen der Kinder- und Jugendliteratur Informationen sammeln und dieses Wissen in Bezug zu einzelnen Texten setzen.", zyklus: "3", reihenfolge_index: "e", schluesselwoerter: ["Literatur", "Autor/innen", "Jugendliteratur"] },
    { kompetenz_id: "D.6.C.1b", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "C Literarische Texte: Beschaffenheit und Wirkung", kompetenz_titel: "Literarische Texte: Beschaffenheit und Wirkung erkennen", beschreibung: "können Verse, Reime, Lieder und Gedichte rhythmisch nachsprechen oder singen und Takt, Rhythmus und spezifische Wortwahl (z.B. Sprachspiel) als Bereicherung erleben.", zyklus: "1", reihenfolge_index: "b", schluesselwoerter: ["Literatur", "Rhythmus", "Gedichte"] },
    { kompetenz_id: "D.6.C.2e", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "C Literarische Texte: Beschaffenheit und Wirkung", kompetenz_titel: "Literarische Texte: Beschaffenheit und Wirkung erkennen", beschreibung: "können einfache formale und sprachliche Merkmale von literarischen Texten v.a. bei sprachspielerischen Elementen selbstständig erkennen (z.B. Reim, Vers, Strophe, Wortwahl).", zyklus: "2", reihenfolge_index: "e", schluesselwoerter: ["Literatur", "Merkmale", "Sprachspiel"] },
    { kompetenz_id: "D.6.C.3h", fach_name: "Deutsch", hauptbereich: "D.6 Literatur im Fokus", unterbereich: "C Literarische Texte: Beschaffenheit und Wirkung", kompetenz_titel: "Literarische Texte: Beschaffenheit und Wirkung erkennen", beschreibung: "können sich mit unvertrauten literarischen Texten auseinandersetzen (z.B. aus einer anderen Zeit, Theater, unbekanntes Filmgenre) und sich darüber austauschen.", zyklus: "3", reihenfolge_index: "h", schluesselwoerter: ["Literatur", "Genres", "Auseinandersetzung"] }
  ];
};

     // Platzhalter für weitere Fächer – hier kannst du neue Funktionen hinzufügen
     export const getLehrplanMath = () => {
       return [];
       // Füge hier den Lehrplan für Mathe hinzu, z.B.
       // { kompetenz_id: "M.1.A.1", fach_name: "Mathematik", ... },
     };

     export const getLehrplanNMG = () => {
       return [];
       // Füge NMG-Daten hinzu, wenn verfügbar
     };

     // Haupt-Funktion: Gibt Daten basierend auf Fach zurück (erweiterbar)
     export const getLehrplanData = (subject) => {
       switch (subject) {
         case 'Deutsch':
           return getLehrplanDeutsch();
         case 'Mathematik':
           return getLehrplanMath();
         case 'NMG':
           return getLehrplanNMG();
         // Füge weitere cases für neue Fächer hinzu
         default:
           return [];  // Fallback für unbekannte Fächer
       }
     };